[package]
name = "http-proxy-client-async"
version = "0.1.0"
authors = ["MOZGIII <mike-n@narod.ru>"]
edition = "2018"

[dependencies]
http = "0.1"
httparse = "1.3"
futures-preview = "0.3.0-alpha.19"

[dev-dependencies]
merge-io = "0.2"
