[package]
name = "http-proxy-client-async"
version = "0.3.0"
authors = ["MOZGIII <mike-n@narod.ru>"]
edition = "2018"

[dependencies]
http = "0.2"
httparse = "1.3"
futures-io = "0.3"
futures-util = "0.3"

[dev-dependencies]
futures = "0.3"
merge-io = "0.3"
